### PR TITLE
Add gitstatusd-android-armv7l binary

### PR DESCRIPTION
**Pull request by Akianonymus**
Built and tested using termux.

CPU architecture: arm
Android version: 7.1.2
Kernel build information: Linux localhost 3.10.49-g415000d938d #1 SMP PREEMPT Mon Dec 23 13:58:03 CET 2019 armv7l Android

### CODE REVIEW

**Comment by romkatv** [comment]
I don't accept prebuilt binaries from anyone for security reasons. Sorry.

**Comment by Akianonymus** [comment]
> I don't accept prebuilt binaries from anyone for security reasons. Sorry.

Well, fair enough, anyway, doesn't matter, i have uploaded the build script fix, so you can do yourself.

Thank you.

**Comment by Akianonymus** [comment]
Will close this, once the binary is in the repo.

Cheers :)

**Comment by romkatv** [comment]
> Will close this, once the binary is in the repo.

I don't intend to build it, sorry. I provide prebuilt binaries only for a few most popular architectures. 32-bit android din't make the cut.

**Comment by Akianonymus** [comment]
> > Will close this, once the binary is in the repo.
> 
> I don't intend to build it, sorry. I provide prebuilt binaries only for a few most popular architectures. 32-bit android din't make the cut.

Ok, atleast, add a little hint in powerlevel repo what to do if we get errors related to this binary, just a request, and yes android 32 bit is almost dead, but not yet extinct.

**Comment by romkatv** [comment]
> Ok, atleast, add a little hint in powerlevel repo what to do if we get errors related to this binary

Good idea. Done: https://github.com/romkatv/powerlevel10k/commit/0a484d1d994de7febcdb1ffa9c9d2635c65c285d.

**Pull request closed without merging**
