### PR TITLE
Add binary for riscv64 architecture

### PR DESCRIPTION
**Pull request by carlosedp**
Add binary for riscv64 architecture on Linux

### CODE REVIEW

**Comment by romkatv** [comment]
Sorry, I don't accept binaries built in an environment I don't control (security hazard). I also cannot keep adding more binaries to this repository because it doesn't scale (all users have to download all binaries). I don't have a good solution for this problem right now other than for you to keep the binary somewhere locally and set `GITSTATUS_DAEMON=/path/to/gitstatusd`.

Is this good enough?

**Comment by carlosedp** [comment]
I ended up adding this to my .zshrc:

```
if [ $(uname -m) == "riscv64" ]; then
    GITSTATUS_DAEMON=/usr/local/bin/gitstatusd-linux-riscv64
fi
```

Thanks

**Comment by romkatv** [comment]
👍 

In most cases you can use `$CPUTYPE` instead of `(uname -m)`. Saves a fork.

**Comment by romkatv** [comment]
By the way, did gitstatusd compile out of the box on linux-riscv64 or did you have to change anything?

**Comment by carlosedp** [comment]
Compiled perfectly, no changes at all. Thanks for the $CPUTYPE tip!

**Pull request closed without merging**
