### PR TITLE
add fish bindings

### PR DESCRIPTION
**Pull request by wodesuck**
Basically translate from Bash bindings, but since fish doesn't support setting redirection for the current shell (which is `exec {_REQ_FD}>$req_fifo {_RESP_FD}<$resp_fifo` in bash) and `read` with timeout, a `netcat` process listening a unix socket is run in background, to redirect requests and responses, and use `nc -w $timeout` as the replacement of `read -t $timeout`. Could be improve if these two issues are solved https://github.com/fish-shell/fish-shell/issues/3948 https://github.com/fish-shell/fish-shell/issues/1134

### CODE REVIEW

**Comment by romkatv** [comment]
Thanks for sending the PR.

Disclaimer: I know very little about Fish and don't use it myself. My questions are probably silly.

`nc` is missing from many distributions by default. Is it possible to use something else that's more broadly available?

There are so many forks in `gitstatus_query`. Is it possible to reduce their number to 0, or at most 1?

The comments suggest that some of the complexity and the necessity to fork stems from Fish's lack of read with timeout. Would this code be much simpler/faster if you drop support for timeouts?

Is it possible to put everything in two files the same way it's done for Bash, one file for the bindings and another for prompt formatting?

If you type `exec fish` after initializing gitstatus in Fish, do the background processes (`nc` and `gitstatusd`) die? If yes, what mechanism ensures this?

The same question as above but for `/bin/kill -9 $fish_pid` instead of `exec fish`. `gitstatusd` will terminate on its own but I'm not sure about `nc`.

**Comment by wodesuck** [comment]
> nc is missing from many distributions by default. Is it possible to use something else that's more broadly available?

Script language with socket lib (such as python) could also be used. But using `nc` is simpler, and it's easy to get in most of platforms (at least more popular than fish I guess).

> There are so many forks in gitstatus_query. Is it possible to reduce their number to 0, or at most 1?

I don't surely understand the meaning of "so many forks" in `gitstatus_query`, maybe you mean calling external command? If you mean that, I think it's difficult to avoid.

> The comments suggest that some of the complexity and the necessity to fork stems from Fish's lack of read with timeout. Would this code be much simpler/faster if you drop support for timeouts?

No, the main problem is fish's lack of equivalent of `exec {_REQ_FD}>$req_fifo {_RESP_FD}<$resp_fifo`.

> Is it possible to put everything in two files the same way it's done for Bash, one file for the bindings and another for prompt formatting?

https://github.com/jorgebucaran/fish-cookbook#should-function-names-and-file-names-match

Using same function name as file name is a common practice in fish. We may move functions expect `fish_prompt` into a single file, and manual source in `fish_prompt.fish`, but I think we should follow the fish's way.

> If you type exec fish after initializing gitstatus in Fish, do the background processes (nc and gitstatusd) die? If yes, what mechanism ensures this?
>
> The same question as above but for /bin/kill -9 $fish_pid instead of exec fish. gitstatusd will terminate on its own but I'm not sure about nc.

After doing some experiments, I found that calling `exec fish`, the background processes will die after fish exit. There are 2 `nc` and 2 `gitstatusd` (old one and new one) just after `exec`, and they will all die after fish exit.

But, although background process are exit, there will be a unix socket file (the old one) that are not being `rm`. Similar thing happen with `kill -9 $fish_pid`. After some debugging, I found that is because, we define `gitstatus_stop` as a [fish event handler](https://fishshell.com/docs/current/index.html#event) on event fish_exit for cleaning up, and it won't emit if `exec` or `kill -9`. But I still not clearly understand why background processes will die without calling `gitstatus_stop`.

**Comment by romkatv** [comment]
> I don't surely understand the meaning of "so many forks" in `gitstatus_query`, maybe you mean calling external command? If you mean that, I think it's difficult to avoid.

Yes, sorry about the jargon. When you call an external program, shell calls `fork()` (see `man 2 fork`) and `exec()` (see `man 3 exec`) or their equivalents. `fork()` is about 1000 times more expensive than anything else you could do in shell. A single fork in `gitstatus_query` would make it *much* slower in fish than in bash or zsh. The current fish implementation seems to result in 4 calls to `fork()`. This could be tolerable on Linux but on systems with slower `fork()` (e.g., Windows) it'll probably have noticeable lag.

> After doing some experiments, I found that calling `exec fish`, the background processes will die after fish exit. There are 2 `nc` and 2 `gitstatusd` (old one and new one) just after `exec`, and they will all die after fish exit.

So after calling `exec fish` you end up with two instances of `nc` and `gitstatusd`? That's bad. When using bash or zsh, the old daemons terminal on exec. Those daemons are useless anyhow, so they shouldn't stick around.

> But, although background process are exit, there will be a unix socket file (the old one) that are not being `rm`.

Is there a way to fix this?

---

To be upfront about it, I wouldn't be comfortable maintaining fish bindings in this state. If it's not feasible to remove forks from `gitstatus_query` and to fix cleanup on `exec`, I suggest to keep fish bindings in a separate repository. This repository could be a fork of romkatv/gitstatus, or somehow depend on it. What do you think?

**Comment by wodesuck** [comment]
The fastest way to do `gitstatus_query` that I can image, is to implement a client in C++, that would reduce number of forks to 1. Furthermore, if `gitstatusd` support listening on socket instead of stdio, we could get rid of the extra `nc` daemon process.

Or, we could just wait fish for the support of `exec` style redirection and read timeout. https://github.com/fish-shell/fish-shell/issues/3948 & https://github.com/fish-shell/fish-shell/issues/1134

> So after calling exec fish you end up with two instances of nc and gitstatusd? That's bad. When using bash or zsh, the old daemons terminal on exec. Those daemons are useless anyhow, so they shouldn't stick around.

I didn't found ways to detect `exec` in fish. But I don't think this is a big deal, since `exec` is rarely used in an interactive shell.

> But, although background process are exit, there will be a unix socket file (the old one) that are not being rm.
>
> Is there a way to fix this?

We could try to wrap the `nc` daemon process, and add a `trap` for cleaning up. Another way is to use port instead of unix socket, and we could avoid the trouble for cleaning up files.

> To be upfront about it, I wouldn't be comfortable maintaining fish bindings in this state. If it's not feasible to remove forks from gitstatus_query and to fix cleanup on exec, I suggest to keep fish bindings in a separate repository. This repository could be a fork of romkatv/gitstatus, or somehow depend on it. What do you think?

It' fine to keep it in my own fork.

**Comment by romkatv** [comment]
> The fastest way to do `gitstatus_query` that I can image, is to implement a client in C++, that would reduce number of forks to 1. Furthermore, if `gitstatusd` support listening on socket instead of stdio, we could get rid of the extra `nc` daemon process.

Before embarking on the optimization journey it's important to have a clear metric to work with. You can measure the overhead of shell bindings by timing `gitstatus_query` when the current directory is not in a Git repository. In Bash you can do this by typing `bash --norc` and then copy-pasting the following command:

```bash
bash --norc
mkdir -p /tmp/not-a-git-repo
cd /tmp/not-a-git-repo
git clone --depth=1 https://github.com/romkatv/gitstatus.git /tmp/gitstatus
source /tmp/gitstatus/gitstatus.plugin.sh
gitstatus_start
time { unset VCS_STATUS_RESULT; for i in {1..1000}; do gitstatus_query; done; echo $VCS_STATUS_RESULT; }
```

On my machine I get:

```text
norepo-sync

real  0m0.772s
user  0m0.561s
sys   0m0.231s
```

(It's a good idea to print `$VCS_STATUS_RESULT` at the end to avoid silly mistakes when you are timing something different from your intention.)

This says that `gitstatus_query` takes 0.772 milliseconds. This is a little high because I don't optimize Bash implementation much. The same benchmark in Zsh gives more reasonable latency of 0.182 milliseconds.

Try it with Fish and see what you get.

Writing a native client can be a resonable choice if your current implementation has unacceptably high latency on some systems that you want to support. What constitues unacceptably high latency and which systems are worth supporting are choices that you need to make.

If you go with a native client, I would recommend choosing a language with good cross-platform compilation support. It's much easier to support many platforms if you write code in Go or Rust than if you write it in C++. The performance of the chosen language matters only where it concerns startup/shutdown time. There is very little actual work the client binary will need to perform.

You can also implement the client in some popular scripting language. As long the language has the APIs you need, and as long as the interpreter is fast to start and shutdown, there should be no downsides compared to a native implementation. The advantage is the ease of distribution. It's better to have a dependency on `perl` (just an example; I don't know if it qualifies) than to to ship a custom native binary.

> I didn't found ways to detect `exec` in fish. But I don't think this is a big deal, since `exec` is rarely used in an interactive shell.

Perhaps rarely used in Fish? I use it all the time in Bash and Zsh. It's the best way to "restart shell" after changing rc files.

> We could try to wrap the `nc` daemon process, and add a `trap` for cleaning up. Another way is to use port instead of unix socket, and we could avoid the trouble for cleaning up files.

Traps won't run on `exec` or when the parent process terminates abnormally (e.g., `SIGKILL`).

The existing Bash gitstatus bindings may not be the best model for Fish. Zsh bindings work quite differently and better. Within powerelvel10k there is another daemon, and that one is better still. I plan to rewrite Zsh bindings to use the same technique as in powerlevel10k.

I don't know what tools are available in Fish so I cannot suggest the best way to launch gistatusd and start talking to it. My point is that there might be alternatives to the Bash approach that are more suitable for Fish due to being simpler, more reliable or faster. Exploring them might pay off.

> It' fine to keep it in my own fork.

Let's go with that then.

You can still ask me for code reviews if you like. I'm happy to help where I can.

**Comment by romkatv** [comment]
Shall we close this PR? Feel free to ping me whenever you need feedback on code/ideas.

**Comment by mattgreen** [comment]
Yesterday, I took a stab at fish bindings using fish idioms and ended up in a similar predicament as the OP. 

The crux of the issue: fish's inability to keep an fd open prevents us from cheaply communicating with `gitstatusd`. I'm not sure when such constructs will land, either.

This may be a separate issue, but if you'd be open to changes, I'd be propose some smaller changes to work towards this:

1. Add abstract `Reader` base class. `RequestReader` implements this class to read from stdin. Rename `RequestReader` to `StdinRequestReader`.
2. Add a `UnixDatagramRequestReader` class that reads from a Unix domain datagram socket. Used if the user specifies `--domain-sock <path>` on the command line. (Users can use `socat` or maybe `nc` to communicate with it in the meantime.)

**Comment by romkatv** [comment]
> if you'd be open to changes

I am.

> Add abstract `Reader` base class.

Not to these changes.

**Pull request closed without merging**
