### PR TITLE
respect existing prompt commands in bash

### PR DESCRIPTION
**Pull request by laggardkernel**

### CODE REVIEW

**Comment by romkatv** [comment]
If you are sourcing `gitstatus.prompt.sh` but don't like the exact prompt it's setting, you can override `PS1`  and/or `PROMPT_COMMAND` afterwards.

```bash
source ~/gitstatus/gitstatus.prompt.sh

PROMPT_COMMAND='...'
PS1='...'
```

Does this work for you?

**Comment by laggardkernel** [comment]
No. You misunderstood me. I'm not talking about the style of the prompt. 

`PROMPT_COMMAND` also serves as a hook before you enter commands. There're other commands/functions not for prompt rendering hooked on it as well. If we assign `PROMPT_COMMAND=gitstatus_prompt_update` directly, the functions hooked before will be overwritten. I'm trying to keep them.

```bash
$ echo "$PROMPT_COMMAND"
_direnv_hook;echo ;_fasd_prompt_func;gitstatus_prompt_update
```

**Comment by romkatv** [comment]
Thanks for the explanation.

There are three ways to use gitstatus from Bash. From the easiest to the most flexible:

1. Simply source `gitstatus.prompt.sh`. Works out of the box and serves as an example for advanced users.
2. Source `gitstatus.prompt.sh` and override `PS1` and/or `PROMPT_COMMAND` _afterwards_. Affords some flexibility in prompt formatting and integration with Bash plugins such as Fasd. Requires understanding of Bash prompt.
3. Copy and modify the parts of `gitstatus.prompt.sh` that you find useful. Most flexible. Note that `gitstatus.prompt.sh` is a tiny script with virtually all code concerned with the _formatting_ of Git prompt. It's perfectly fine to copy and modify it. The heavy lifting of _obtaining_ Git info is done by `gitstatus.plugin.sh` and C++. Copying and modifying _these_ is best avoided.

My initial response on this PR was a suggestion to use (2). That is, instead of setting `PROMPT_COMMAND` and _then_ sourcing `gitstatus.prompt.sh`, can you instead source `gitstatus.prompt.sh` _first_ and then add `_fasd_prompt_func` to it? If this isn't possible for some reason, you can either go with (3) or employ an extended version of (2):

```bash
my_prompt_command=${PROMPT_COMMAND// }
source gitstatus.prompt.sh
if [[ "$my_prompt_command" != *gitstatus_prompt_update* ]]; then
  my_prompt_command+=${my_prompt_command:+;}
  my_prompt_command+=$PROMPT_COMMAND
fi
PROMPT_COMMAND=$my_prompt_command
```

Note that the condition under `if` is an approximation. This code may need to be changed if you are using some kind of framework for defining `precmd` hooks. If you are using Bash-it, it should be like this:

```bash
my_prompt_command=$PROMPT_COMMAND
source gitstatus.prompt.sh
PROMPT_COMMAND=$my_prompt_command
safe_append_prompt_command gitstatus_prompt_update
```

`gitstatus.prompt.sh` doesn't do this sort of thing by itself for several reasons.

- Appending to `PROMPT_COMMAND` is non-trivial. Making it work on all systems may even be impossible.
- Preserving the existing `PROMPT_COMMAND` while completely overriding `PS1` would be inconsistent and surprising. In the worst case users may be sourcing `gitstatus.prompt.sh` after some other Bash theme that sets up expensive hooks in `PROMPT_COMMAND` in order to use their results in `PS1`. If the users are satisfied with the look of their prompt after sourcing `gitstatus.prompt.sh`, they may miss the fact that their prompt is slow due to still calling hooks from their old theme that no longer have any effect.
- If the existing logic of `gitstatus.prompt.sh` doesn't work for someone, there is always an escape hatch. They can either modify `PS1` and/or `PROMPT_COMMAND` after sourcing the file or copy parts of it instead of sourcing in the first place.

Does this make sense?

**Comment by laggardkernel** [comment]
I got it.

**Pull request closed without merging**
